name: Jason Berman Director of Photography
favicon: null
layout_spectrum: 0.10319151263684034
typography_spectrum: 0.4364710580557585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5062483293004334
  lightness: 0.6606590033043176
  saturation: 0.09866600716486573
  rhythmicContrast: 0.05924349674023688
purpose: []
